hello/urls.py
from django.conf.urls import url
from . import views

app_name = 'hello'

urlpatterns = [
    url(r'^$', views.hello_world, name='hello_world'),
    url(r'^template/$', views.hello_template, name='hello_template'),
    url(r'^if/$', views.hello_if, name='hello_if'),
    url(r'^for/$',views.hello_for, name='hello_for'),
    url(r'^get/$', views.hello_get_query, name='hello_get_query'),
    url(r'^forms/$', views.hello_forms, name='hello_forms'),
    url(r'^form_samples/$', views.hello_forms2, name='hello_forms2'),
    url(r'^models/$', views.hello_models, name='hello_models')
]

mysite2/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^hello/', include('hello.urls', namespace='hello')),
]

hello/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    # id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    last_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    email_address = models.EmailField(max_length=255, unique=True)
    memo = models.TextField(null=True)

class Hello(models.Model):
    your_name = models.CharField(max_length=10)

    def __str__(self):
        return "<{0}>".format(self.your_name)

hello/forms.py
from django import forms


class HelloForm(forms.Form):
    your_name = forms.CharField(
        label='名前',
        max_length=20,
        required=True,
        widget=forms.TextInput()
    )

EMPTY_CHOICES = (
    ('', '-'*10),
)

GENDER_CHOICES = (
    ('man', '男'),
    ('woman', '女')
)

FOOD_CHOICES = (
    ('apple', 'りんご'),
    ('beef', '牛肉'),
    ('bread', 'パン'),

)


class SampleForm(forms.Form):
    age = forms.IntegerField(
        label='年齢',
        min_value=0,
        max_value=200,
        required=True,
    )

    birthday = forms.DateField(
        label='生年月日',
        required=True,
        input_formats=[
            '%Y-%m-%d',  # 2010-01-01
            '%Y/%m/%d',  # 2010/01/01
        ]
    )

    send_message = forms.BooleanField(
        label='送信する',
        required=False,
    )

    gender_r = forms.ChoiceField(
        label='性別',
        widget=forms.RadioSelect,
        choices=GENDER_CHOICES,
        required=True,
    )

    gender_s = forms.ChoiceField(
        label='性別',
        widget=forms.Select,
        choices=EMPTY_CHOICES + GENDER_CHOICES,
        required=False,
    )

    food_s = forms.ChoiceField(
        label='食べ物',
        widget=forms.SelectMultiple,
        choices=FOOD_CHOICES,
        required=True,
    )

    food_c = forms.ChoiceField(
        label='食べ物',
        widget=forms.CheckboxSelectMultiple,
        choices=FOOD_CHOICES,
        required=True,
    )

hello/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from datetime import datetime
from . import forms,models

def hello_world(request):
    return HttpResponse('Hello World!')

## 変数を表示しよう
def hello_template(request):
    d = {
        'hour': datetime.now().hour,
        'message': 'Sample message',
    }
    return render(request, 'index.html', d)

## 条件によって表示を切り替えよう
def hello_if(request):
    d = {
        'is_visible': False,
        'empty_str': '',
    }
    return render(request, 'if.html', d)

## 配列の要素を扱おう
def hello_for(request):
    d = {
        'objects': range(10),
    }
    return render(request, 'for.html', d)

## ビュー関数で、画面から入力したデータを扱おう
def hello_get_query(request):
    d = {
        'your_name': request.GET.get('your_name')
    }
    return render(request, 'get_query.html', d)

## ビュー関数からFormクラスを使おう
def hello_forms(request):
    form = forms.HelloForm(request.GET or None)
    if form.is_valid():
        message = 'データ検証に成功しました'
    else:
        message = 'データ検証に失敗しました'
    d = {
        'form': form,
        'message': message,
    }
    return render(request, 'forms.html', d)

def hello_forms2(request):
    d = {
        'form': forms.SampleForm(),
    }
    return render(request, 'form_samples.html', d)

## 画面から入力されたデータをデータベースに保存しよう
def hello_models(request):
    form = forms.HelloForm(request.POST or None)
    if form.is_valid():
        models.Hello.objects.create(**form.cleaned_data)
        return redirect('hello:hello_models')

    d = {
        'form': form,
        'hello_qs': models.Hello.objects.all().order_by('-id')
    }
    return render(request, 'models.html', d)

hello/templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

hello/templates/for.html
{% extends "base.html" %}

{% block body %}

<!--内容-->
{% for idx in objects %}
    {{ idx }}<br>
{% endfor %}
<!--内容〆-->

{% endblock %}

hello/templates/form_samples.html
{% extends "base.html" %}

{% block body %}
  <form method="get" action="">
    {{ form.age.label }}：
    {{ form.age }}
    <hr>

    {{ form.gender_r.label }}：
    {% for gender in form.gender_r %}
      {{ gender }}
    {% endfor %}
    <hr>

    {{ form.gender_s.label }}：
    {{ form.gender_s }}
    <hr>

    {{ form.send_message.label }}：
    {{ form.send_message }}
    <hr>

    {{ form.birthday.label }}：
    {{ form.birthday }}
    <hr>

    {{ form.food_s.label }}：
    {{ form.food_s }}
    <hr>

    {{ form.food_c.label }}：
    {% for food in form.food_c %}
      {{ food }}
    {% endfor %}
    <hr>

  </form>
{% endblock %}

hello/templates/forms.html
{% extends "base.html" %}

{% block body %}

  {{ message }}
  <hr>
  <form method="get" action="">
    {{ form.errors.your_name }}
    <label>{{ form.your_name.label }} {{ form.your_name }}</label><br>

    {{ form.errors.gender }}
    <label>{{ form.gender.label }} {{ form.gender }}</label><br>

    {{ form.errors.memo }}
    <label style="vertical-align: top;">{{ form.memo.label }} {{ form.memo }}</label><br>

    <input type="submit" value="送信">
  </form>

{% endblock %}

hello/templates/get_query.html
{% extends "base.html" %}

{% block body %}

  <form action="" method="get">
      <label>名前:<input type="text" size="20" name="your_name"></label>
      <input type="submit" value="送信">
  </form>
  {% if your_name %}
      {{ your_name }}さん、こんにちは。
  {% endif %}

{% endblock %}

hello/templates/if.html
{% extends "base.html" %}
{% block body %}

<!--内容-->
{% if is_visible %}
  is_visibleがTrueなので表示します。<br>
{% else %}
  is_visibleがFalseなので表示します。<br>
{% endif %}

{% if empty_str|length > 0 %}
  empty_strの文字数は{{ empty_str|length }}です。
{% else %}
  empty_strが空です。<br>
{% endif %}
<!--内容〆-->

<div>
  <a href="{% url 'hello:hello_template' %}">戻る</a>
</div>

{% endblock %}

hello/templates/index.html
{% extends "base.html" %}

{% block title %}変数の練習{% endblock %}

{% block body %}

  <!--内容-->
  <div>
    {{ hour }}時です。<br>
    {{ message }}
  </div>
  <br>
  <div>
    <a href="{% url 'hello:hello_world' %}">hello_world</a><br>
    <a href="{% url 'hello:hello_template' %}">変数を表示しよう(template)</a><br>
    <a href="{% url 'hello:hello_if' %}">条件によって表示を切り替えよう(if)</a><br>
    <a href="{% url 'hello:hello_for' %}">配列の要素を扱おう(for)</a><br>
    <a href="{% url 'hello:hello_get_query' %}">ビュー関数で、画面から入力したデータを扱おう</a><br>
    <a href="{% url 'hello:hello_forms' %}">ビュー関数からFormクラスを使おう_その1</a><br>
    <a href="{% url 'hello:hello_forms2' %}">ビュー関数からFormクラスを使おう_その2</a><br>
  </div>
  <!--内容〆-->

{% endblock %}

hello/templates/models.html
{% extends "base.html" %}

{% block body %}
  <h1>your_nameを登録する</h1>
  <h2>登録</h2>
  <form method="post" action="">
    {{ form.errors.your_name }}
    <label>{{ form.your_name.label }} {{ form.your_name }}</label><br>
    <input type="submit" value="送信">
    {% csrf_token %}
  </form>
  <hr>
  <h2>一覧</h2>
  {% for h in hello_qs %}
    {{ h.your_name }}<br>
  {% endfor %}
  
{% endblock %}